# GitHub Secret Scanning Configuration
# Firebase web API keys are public by design and safe when properly restricted

paths-ignore:
  - 'build/web/**'
  - '**/main.dart.js'
  - '**/flutter_service_worker.js'
  - 'lib/firebase_options.dart'
